### PR TITLE
New WPF client project, bug fixes to allow SDK to work with .NET client framework & other minor fixes

### PR DESCRIPTION
**Pull request by jeetumaker**

### CODE REVIEW

**Comment by Ku6opr** [comment]
Hi. First for all thank you for contributing into Countly SDK. I have reviewed you merge request and have some comments for you:
- windows/Countly folder contains PCL library (not obvious name, we should rename it). I have checked - it can be referenced from WPF project, so **we should not create another solution for WPF and concentrate on portable library** to support as much platforms as we can. Probably, net35 folder is also redundant - as we can add .NET in target for PCL
- I saw you used IsoStorage in net35 and WPF project, but file is only in WPF, so project doesn't compiles. BTW, PCL uses Isolated Storage, so you don't need to create it yourself

**Comment by jeetumaker** [comment]
Thanks for your prompt feedback.. Here are my comments :


   - windows/Countly folder contains PCL library (not obvious name, we
   should rename it). I have checked - it can be referenced from WPF project,
   so *we should not create another solution for WPF and concentrate on
   portable library* to support as much platforms as we can. Probably,
   net35 folder is also redundant - as we can add .NET in target for PCL\

         =>  I believe its the .NET Framework compatibility issue more than
WPF.  First of all the libraries used for Task (async/await) in the project
works for .NET 3.5.  For client apps targeting .NET 4.0 there is another
library from Microsoft. Of course for 4.5 on wards we will not need this
library at all.  So we need to have separate projects at least for these 3
frameworks even with PCL since the library needs support for async/await.
Secondly some of the client apps on WPF could limit to .NET Client profile
which is a subset of the full framework and therefore doesn't support
certain assemblies like System.Web ..  Therefore to not have any impact on
the existing PCL project for .NET 3.5, I created a separate one for WPF
which basically links with the same code base.


   - I saw you used IsoStorage in net35 and WPF project, but file is only
   in WPF, so project doesn't compiles. BTW, PCL uses Isolated Storage, so you
   don't need to create it yourself

        => I agree with you .. I should move  this to the same Storage
folder and link it from there .. PCL may use isolated storage when there is
no option and the app itself is isolated.  However for classic desktop
apps, it tries to store in the same location where the app is deployed
which is most commonly installed in "program files" folder.  Many of our
app users do not have permissions to write in this folder as result of
which the SDK fails persisting.


Please let me know if you want me to go ahead with the IsoStorage folder
move ..

Thanks & Regards
Jeetu

**Comment by Ku6opr** [comment]
can we use isolated storage only across SDKs to save data? probably we should not separate between different places

**Comment by jeetumaker** [comment]
I completely agree.. So you may to replace the current storage.cs with isostorage ?

**Comment by Ku6opr** [comment]
yes, do it please

**Comment by jeetumaker** [comment]
Pl disregard my previous msg ..

Iso storage implementation is different across windows platforms .. some like win forms dont support isostorage .. so we would need separate implementation regardless.. another alternative could be to use compilation conditions in project files to drive which one to use..

**Comment by Ku6opr** [comment]
as we have different projects for 3.5, 4.0 client profile and pcl for 4.5 an above, let's separate implementation of storage between them

**Comment by jeetumaker** [comment]
done .. Please check my latest commit and let me know if any issues/concerns. Thanks

**Pull request merged**
